### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by princessfrombabylon99** [tomk1v/first-order-coupon-module#1]
I am running Magento on PHP 8.3 , could you make this module compatible?

**Comment by tomk1v** [comment]
Could you confirm if this module is currently incompatible with PHP 8.3? If you’re encountering any specific errors, could you please provide the error messages or screenshots? This information will help us identify compatibility issues and work on a potential solution. Thank you!

> PHP 8.3

**Comment by princessfrombabylon99** [comment]
I am on a production mode,still I tried to upload this module I followed these commands 
`cd /path/to/your/magento2/installation/app/code`
code folder did not exist , so I created one.
`/var/www/html/magento2/app/ code# git clone https://github.com/tomk1v/first-order-rule-module.git`
This command pulled the file 'first-order-rule-module'
`/var/www/html/magento2# bin/magento module:enable Intership_FirstOrderRule`
**Unknown module(s): 'Intership_FirstOrderRule'**
![image](https://github.com/user-attachments/assets/5500810d-078f-4db1-98b3-0e1f69bdf49e)

**Comment by tomk1v** [comment]
It seems the issue is due to the module’s folder structure after cloning. Magento expects the module files to be in a specific directory structure under app/code. Please review the README.md file instructions and code repository. Here are the steps to resolve this:

**Solution:**

- The module should be at app/code/Intership/FirstOrderRule. Try to clone the repo with the following:
 `git clone https://github.com/tomk1v/first-order-rule-module.git app/code/Intership/FirstOrderRule`

Also, I have verified that this module is compatible with PHP 8.3 and works **without** any issues.
